### ISSUE TITLE
[Question] 0.12是否支持Gremlin Java Client链接，如何管理事务

### ISSUE THREAD

**Issue by haoming06** [apache/incubator-hugegraph#1871]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: 4 CPUs, 16G RAM, Centos 7.x 

### Your Question (问题描述)

使用hugegraph-client 中GraphManager的addVertices、addEdges方法批量插入数据，先批量插顶点再添加边，并不能在一个事务中，查阅资料之前的版本不支持。
看源码中使用gremlin 的graph().tx() 手动控制事务，但本人测试查询会报错。如下：
server端使用默认配置,0.12依赖了gremlin 3.4.3版本
+ 通过使用gremlin console 3.4.3 产生异常
`gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Configured 192.168.100.222/192.168.100.222:8182
gremlin> :remote console
==>All scripts will now be sent to Gremlin Server - [192.168.100.222/192.168.100.222:8182] - type ':remote console' to return to local mode
gremlin> g.V().count()
Index: 121, Size: 0
Type ':help' or ':h' for help.
Display stack trace? [yN]`

+ 代码 gremlin-core 与 gremlin-driver 3.4.3 请求，错误信息如下
` The traversal source [g] for alias [g] is not configured on the server.`

问题如下：

1 . 0.12版本是否支持使用gremlin-client请求
2. 如何将批量操作放到一个事务中

**Comment by javeme** [comment]
问题分别解答如下：

> 1 . 0.12版本是否支持使用gremlin-client请求

支持的，使用 `g` 之前，需要先绑定 `g = graph.traversal()`

> 2. 如何将批量操作放到一个事务中

通过一个请求发送给server的Gremlin语句都是放在一个事务里面的（服务端自动开发/关闭），https://hugegraph.apache.org/docs/clients/restful-api/gremlin/

**Comment by javeme** [comment]
请尝试使用conf下面的默认配置文件`remote-objects.yaml`试试：
```yaml
hosts: [localhost]
port: 8182
serializer: {
  className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0,
  config: {
    serializeResultToString: false,
    ioRegistries: [com.baidu.hugegraph.io.HugeGraphIoRegistry]
  }
} 
```
