### ISSUE TITLE
[Bug] prometheus metric format is invalid

### ISSUE THREAD

**Issue by qwtsc** [apache/incubator-hugegraph#2354]
### Bug Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

hugegraph in k8s using prometheus and grafana as service monitor.

### Expected & Actual behavior (期望与实际表现)

![image](https://github.com/apache/incubator-hugegraph/assets/34210641/abfdfe32-5fd7-4146-a407-d3847b475424)
prometheus metrics format is invalid. After some investigations and code review, I think that the problem would probably be that this [PR](https://github.com/apache/incubator-hugegraph/pull/2286) do not use the correct data exposition format that prometheus community required. The acceptable histogram format can be viewed as follows:
```
# A histogram, which has a pretty complex representation in the text format:
# HELP http_request_duration_seconds A histogram of the request duration.
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_bucket{le="0.05"} 24054
http_request_duration_seconds_bucket{le="0.1"} 33444
http_request_duration_seconds_bucket{le="0.2"} 100392
http_request_duration_seconds_bucket{le="0.5"} 129389
http_request_duration_seconds_bucket{le="1"} 133988
http_request_duration_seconds_bucket{le="+Inf"} 144320
http_request_duration_seconds_sum 53423
http_request_duration_seconds_count 144320
```
and I do also think the correct metric type here is supposed to be `summary` rather than `histogram` according to the prometheus [best practice](https://prometheus.io/docs/practices/histograms/) documentation.

By the way, I am willing to provide a PR to fix this issue as well as grafana dashboard configuration after I figure it out .

**Comment by qwtsc** [comment]
And metric name is also invalid. There are not allowed to have / or $, so this snippet of code should change to the following.
```java
    public static String replaceDotDashInKey(String orgKey) {
        return orgKey.replace(".", "_").replace("-", "_").replace("/", "_").replace("$", "_");
    }
```

**Comment by JackyYangPassion** [comment]
Hi @qwtsc , thanks for reporting the issue.
Welcome to submit PR for fixes

**Comment by imbajin** [comment]
@SunnyBoy-WYH could u check the issue when free

**Comment by SunnyBoy-WYH** [comment]
@qwtsc Thanks for your report, welcome to submit PR ; but can you introduce the request path and something else that we can recurrent it ?

**Comment by qwtsc** [comment]
request path is just /metric. check the following prometheus service monitor.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-hugegraph
  # Change this to the namespace the Prometheus instance is running in
  namespace: default
  labels:
    app: hugegraph
    release: prometheus
spec:
  selector:
    matchLabels:
      name: hugegraph
  namespaceSelector:
    matchNames:
    - hugegraph-e2e
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
```
