### ISSUE TITLE
[Bug] JRaft maxEntriesSize configuration parameters do not take effect

### ISSUE THREAD

**Issue by JackyYangPassion** [apache/incubator-hugegraph#2629]
### Bug Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: master
- Backend: HStore

### Expected & Actual behavior (期望与实际表现)

application.yml 
```
raft:
  # raft 缓存队列大小
  disruptorBufferSize: 1024
  address: 127.0.0.1:8510
  max-log-file-size: 600000000000
  # 快照生成时间间隔，单位秒
  snapshotInterval: 1800
  maxEntriesSize: 2048

```
