### ISSUE TITLE
[Bug] 使用 docker-compose 部署 hugeGraph + Cassandra 作为后端 ,运行后报错

### ISSUE THREAD

**Issue by Tommu10ve** [apache/incubator-hugegraph#2768]
### Bug Type (问题类型)

None

### Before submit

- [x] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: :1.5.0(Apache Release Version)
- Backend: Cassandra nodes, HDD
- OS: 16 CPUs, 47G RAM,  Anolis OS  8.9

### Expected & Actual behavior (期望与实际表现)

部署脚本
```

version: "3"
services:
  graph:
    image: hugegraph/hugegraph
    container_name: cas-server
    ports:
      - 48080:8080
    environment:
      hugegraph.backend: cassandra
      hugegraph.serializer: cassandra
      hugegraph.cassandra.host: cas-cassandra
      hugegraph.cassandra.port: 9042

    networks:
      - ca-network
    depends_on:
      - cassandra
    healthcheck:
      test: ["CMD", "bin/gremlin-console.sh", "--" ,"-e", "scripts/remote-connect.groovy"]
      interval: 10s
      timeout: 30s
      retries: 3

  cassandra:
    image: cassandra:4.0.10
    container_name: cas-cassandra
    ports:
      - 7000:7000
      - 9042:9042
    security_opt:
      - seccomp:unconfined
    networks:
      - ca-network
    healthcheck:
      test: ["CMD", "cqlsh", "--execute", "describe keyspaces;"]
      interval: 10s
      timeout: 30s
      retries: 5

  hubble:
    image: hugegraph/hubble:1.5.0
    container_name: hubble
    ports:
      - 8088:8088

networks:
  ca-network:
```

部署之后 使用 cassandra 失败

```
Hugegraph server are waiting for storage backend...
cas-server     | Hugegraph server are waiting for storage backend...
cas-server     | init hugegraph with non-auth mode
cas-server     | Initializing HugeGraph Store...
cas-server     | 2025-05-21 09:49:40 [main] [ERROR] o.a.h.StandardHugeGraph - Failed to load backend store provider: backend is illegal: cassandra
cas-server     | Exception in thread "main" java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [class org.apache.hugegraph.HugeFactory]
cas-server     |        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:84)
cas-server     |        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:72)
cas-server     |        at org.apache.hugegraph.cmd.InitStore.initGraph(InitStore.java:103)
cas-server     |        at org.apache.hugegraph.cmd.InitStore.main(InitStore.java:87)
cas-server     | Caused by: java.lang.reflect.InvocationTargetException
cas-server     |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
cas-server     |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
cas-server     |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
cas-server     |        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
cas-server     |        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:80)
cas-server     |        ... 3 more
cas-server     | Caused by: org.apache.hugegraph.HugeException: Failed to load backend store provider
cas-server     |        at org.apache.hugegraph.StandardHugeGraph.<init>(StandardHugeGraph.java:236)
cas-server     |        at org.apache.hugegraph.HugeFactory.open(HugeFactory.java:88)
cas-server     |        at org.apache.hugegraph.HugeFactory.open(HugeFactory.java:66)
cas-server     |        ... 8 more
cas-server     | Caused by: java.lang.IllegalStateException: backend is illegal: cassandra
cas-server     |        at com.google.common.base.Preconditions.checkState(Preconditions.java:534)
cas-server     |        at org.apache.hugegraph.util.E.checkState(E.java:64)
cas-server     |        at org.apache.hugegraph.backend.store.BackendProviderFactory.newProvider(BackendProviderFactory.java:70)
cas-server     |        at org.apache.hugegraph.backend.store.BackendProviderFactory.open(BackendProviderFactory.java:59)
cas-server     |        at org.apache.hugegraph.StandardHugeGraph.loadStoreProvider(StandardHugeGraph.java:575)
cas-server     |        at org.apache.hugegraph.StandardHugeGraph.<init>(StandardHugeGraph.java:231)
cas-server     |        ... 10 more
cas-server     | Initialization finished.
cas-server     | Starting HugeGraphServer in daemon mode...
cas-server     | Connecting to HugeGraphServer (http://0.0.0.0:8080/graphs)...OK
```

### Vertex/Edge example (问题点 / 边数据举例)

```javascript

```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript

```

**Comment by imbajin** [comment]
@Tommu10ve @dosu

首先常识一下 Cassandra 版本降低到 3.1x, 印象里 4.x 是有 breaking change 的, 之前尝试过简单适配, 后面发现还是有问题就先回滚了, refer https://github.com/apache/incubator-hugegraph/pull/2300

另外从 1.7 (下一个正式版) 开始, Cassandra 不再是社区主要支持后端, 我们会集中到 RocksDB/HBase 上, 也告知一下

**Comment by Tommu10ve** [comment]
RocksDB能支持分布式大数据量么?

**Comment by Tommu10ve** [comment]
镜像版本设置为 hugegraph/hugegraph:1.5.0 和   cassandra:3.11.19 能正常构建
```
version: "3"

services:
  server:
    image: hugegraph/hugegraph:1.5.0
    container_name: cas-server
    ports:
      - 8080:8080
    environment:
    #   PRELOAD: true
      hugegraph.backend: cassandra
      hugegraph.serializer: cassandra
      hugegraph.cassandra.host: cas-cassandra
      hugegraph.cassandra.port: 9042
    # volumes:
    #   - /data/graph/hugeGraph/example.groovy:/hugegraph/scripts/example.groovy
    networks:
      - ca-network
    depends_on:
      - cassandra
    healthcheck:
      test: ["CMD", "bin/gremlin-console.sh", "--" ,"-e", "scripts/remote-connect.groovy"]
      interval: 10s
      timeout: 30s
      retries: 3

  cassandra:
    image: cassandra:3.11.19
    container_name: cas-cassandra
    ports:
      - 7000:7000
      - 9042:9042
    security_opt:
      - seccomp:unconfined
    networks:
      - ca-network
    healthcheck:
      test: ["CMD", "cqlsh", "--execute", "describe keyspaces;"]
      interval: 10s
      timeout: 30s
      retries: 5

  hubble:
    image: hugegraph/hubble:1.5.0
    container_name: hubble
    ports:
      - 8088:8088

networks:
  ca-network:

volumes:
  hugegraph-data:

```
