### ISSUE TITLE
[Bug] docker部署后,huble无法连接

### ISSUE THREAD

**Issue by Tommu10ve** [apache/incubator-hugegraph#2769]
### Bug Type (问题类型)

None

### Before submit

- [x] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.5.0 (Apache Release Version)

### Expected & Actual behavior (期望与实际表现)

执行脚本
```
version: "3"

services:
  server:
    image: hugegraph/hugegraph:1.5.0
    container_name: cas-server
    ports:
      - 8080:8080
    environment:
      #   PRELOAD: true
      hugegraph.backend: cassandra
      hugegraph.serializer: cassandra
      hugegraph.cassandra.host: cas-cassandra
      hugegraph.cassandra.port: 9042
    # volumes:
    #   - /data/graph/hugeGraph/example.groovy:/hugegraph/scripts/example.groovy
    networks:
      - ca-network
    depends_on:
      - cassandra
    healthcheck:
      test: ["CMD", "bin/gremlin-console.sh", "--" ,"-e", "scripts/remote-connect.groovy"]
      interval: 10s
      timeout: 30s
      retries: 3

  cassandra:
    image: cassandra:3.11.19
    container_name: cas-cassandra
    ports:
      - 7000:7000
      - 9042:9042
    security_opt:
      - seccomp:unconfined
    networks:
      - ca-network
    healthcheck:
      test: ["CMD", "cqlsh", "--execute", "describe keyspaces;"]
      interval: 10s
      timeout: 30s
      retries: 5

  hubble:
    image: hugegraph/hubble:1.5.0
    container_name: hubble
    ports:
      - 8088:8088
  gremlin-server:
    image: tinkerpop/gremlin-server:3.7.3
    container_name: gremlin-server
    ports:
      - 8182:8182

networks:
  ca-network:

volumes:
  hugegraph-data:

```
localhost 链接报错
![Image](https://github.com/user-attachments/assets/17d3a187-6842-4dae-b7b9-9e35fc194bc1)

![Image](https://github.com/user-attachments/assets/0eba9e01-89bc-41e8-89de-bb122fb35df3)

![Image](https://github.com/user-attachments/assets/322ec525-2e7f-4abe-b30b-41742768ea3d)

### Vertex/Edge example (问题点 / 边数据举例)

```javascript

```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript

```
